=== ibq-daw1-1920-25/lmsgi/Unidad_4/Actividad_04_04/schema4_1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="nombre" type="xs:string" />
    <xs:element name="apellidos" type="xs:string" />
    <xs:element name="nota" type="xs:double" />

    <xs:attribute name="dni" type="xs:string" />

        <xs:element name="nota">
        <xs:simpleType>
                <xs:restriction base="xs:decimal">
                        <xs:minInclusive value="0" />
                        <xs:maxInclusive value="10" />
                        <xs:fractionDigits value="2"/>
                </xs:restriction>
        </xs:simpleType>
    </xs:element> 

    <xs:element name="alumno">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre"/>
                <xs:element ref="apellidos"/>
                <xs:element ref="nota"/>
            </xs:sequence>
            <xs:attribute ref="dni"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="datos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="alumno" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ibq-daw1-1920-25/lmsgi/Unidad_4/Actividad_04_04/xml4_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<datos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="schema4_1.xsd">

    <alumno dni = "99887766X">
        <nombre>Dario</nombre>
        <apellidos> Fernandez Alvarez </apellidos>
        <nota> 3.50 </nota>
    </alumno>

    <alumno dni = "11223344A">
        <nombre>Luis</nombre>
        <apellidos> Alvarez Garcia </apellidos>
        <nota> 6.75 </nota>
    </alumno>

    <alumno dni = "556677Z">
        <nombre>Pilar</nombre>
        <apellidos> Rodriguez Menendez </apellidos>
        <nota> 8.25 </nota>
    </alumno>

</datos>
