=== ibq-daw1-1920-25/lmsgi/Unidad_4/Actividad_04_04/schema4_3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
elementFormDefault="qualified">

    <!-- DEFINICIÓN DE LOS ELEMENTOS SIMPLES -->

    <xs:element name="nombre" type="xs:string" />
    <xs:element name="apellidos" type="xs:string" />
    <xs:element name="comentario" type="xs:string" />
    <xs:element name="numero" type="xs:integer" />
    <xs:element name="piso" type="xs:string" />

    <xs:element name="nota">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:minInclusive value="0" />
                <xs:maxInclusive value="10" />
                <xs:fractionDigits value="2"/>
            </xs:restriction>
        </xs:simpleType>   
    </xs:element> 

    <xs:element name="edad">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:pattern value="[15-17]"/>
            </xs:restriction>
        </xs:simpleType>   
    </xs:element> 
 
    <xs:element name="calle">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[A-Z]{18}"/>
            </xs:restriction>
        </xs:simpleType>   
    </xs:element> 

    <xs:element name="poblacion">
            <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="\d{n}"/>
            </xs:restriction>
        </xs:simpleType>   
    </xs:element> 

    <xs:element name="codigo postal">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[0-9]{5}"/>
            </xs:restriction>
        </xs:simpleType>   
    </xs:element> 

    <!-- DEFINICIÓN DE LOS ATRIBUTOS -->

    <xs:attribute name="dni">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="\d{7,8}[A-Z]{1}"/>
            </xs:restriction>
        </xs:simpleType>   
    </xs:attribute> 

    <!-- DEFINICIÓN DE LOS ELEMENTOS COMPLEJOS -->

    <xs:element name="alumno">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre"/>
                <xs:element ref="apellidos"/>
                <xs:element ref="nota"/>
                <xs:element ref="edad" minOccurs="0"/>
                <xs:element ref="comentario"/>
                <xs:element ref="calle" minOccurs="0"/>
                <xs:element ref="piso" minOccurs="0"/>
                <xs:element ref="poblacion" minOccurs="0"/>
                <xs:element ref="codigo postal" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute ref="dni"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="datos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="alumno" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ibq-daw1-1920-25/lmsgi/Unidad_4/Actividad_04_04/xml4_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<datos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="schema4_3.xsd">

    <alumno dni = "99887766X">
        <nombre>Dario</nombre>
        <apellidos> Fernandez Alvarez </apellidos>
        <nota> 3.50 </nota>
        <edad> 45 </edad>
        <comentario> Necesita mejorar </comentario>
        <calle> Comandante Vallespin </calle>
        <numero> 5 </numero>
        <ciudad> Oviedo </ciudad>
        <codigopostal> 33021 </codigopostal>
    </alumno>

    <alumno dni = "11223344A">
        <nombre>Luis</nombre>
        <apellidos> Alvarez Garcia </apellidos>
        <nota> 6.75 </nota>
        <edad> 80 </edad>
        <comentario> Copio de Dario, Alfredo y Pilar </comentario>
    </alumno>

    <alumno dni = "556677Z">
        <nombre>Pilar</nombre>
        <apellidos> Rodriguez Menendez </apellidos>
        <nota> 8.25 </nota>
        <comentario> Copio de todos </comentario>
    </alumno>

    <alumno dni = "66554433T">
        <nombre>Alfredo</nombre>
        <apellidos> Martinez Gonzalez </apellidos>
        <nota> No presentado </nota>
        <edad> 42 </edad>
        <comentario> Estudio en la Universidad de Oviedo </comentario>
        <calle> Galiana </calle>
        <numero> 23 </numero>
        <ciudad> Avil√©s </ciudad>
        <codigopostal> 33400 </codigopostal>
    </alumno>

</datos>
